const GeoLayout goomba_goomba_eyes_closed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, goomba_eyes_closed_switch_eyes_closed_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout goomba_goomba_eyes_dazed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, goomba_eyes_dazed_switch_eyes_dazed_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout goomba_goomba_mouth_open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, goomba_open_mouth_switch_open_mouth_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout goomba_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 150, 100),
		GEO_OPEN_NODE(),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, 0, 90, 0),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_SCALE(LAYER_OPAQUE, 16384),
					GEO_OPEN_NODE(),
						GEO_SCALE(LAYER_OPAQUE, 16384),
						GEO_OPEN_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 304, 0, 0, -51, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, goomba_body_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 203, -271, 71, -90, 0, 141),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, goomba_foot_L_mesh_layer_1),
									GEO_CLOSE_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -113, -271, -184, -90, 0, 141),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, goomba_foot_R_mesh_layer_1),
									GEO_CLOSE_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 27, 243, -33, -2, 0, -1),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, goomba_head_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(3, geo_switch_anim_state),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, goomba_eyes_mesh_layer_1),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, goomba_goomba_eyes_closed),
												GEO_BRANCH(1, goomba_goomba_eyes_dazed),
											GEO_CLOSE_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, goomba_mouth_skinned_mesh_layer_1),
											GEO_SWITCH_CASE(2, geo_switch_goomba_mouth_state),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, goomba_mouth_mesh_layer_1),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, goomba_goomba_mouth_open),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
