extern void scroll_castle_grounds_dl_walls_001_mesh_layer_1_vtx_0();
extern void scroll_castle_grounds_dl_walls_002_mesh_layer_1_vtx_0();
extern void scroll_castle_grounds_dl_walls_003_mesh_layer_1_vtx_0();
extern void scroll_castle_grounds();
