/*
    Parameters are, in this order:
      1  : Symbol category (usually 0 for automatic definition and 1 for manual).
      2  : Symbol name.
      3  : Number of arguments.
      4+ : Pointer type(s) of the arguments in the order they appear in the command.
    Pointer types are available in `data/dynos.cpp.h`.
*/

BHV_SYMBOL(0, BEGIN,                      1, 0)
BHV_SYMBOL(0, DELAY,                      1, 0)
BHV_SYMBOL(1, CALL,                       1, PTYPE_PNTR_BHV)
BHV_SYMBOL(0, RETURN,                     0)
BHV_SYMBOL(1, GOTO,                       1, PTYPE_PNTR_BHV)
BHV_SYMBOL(0, BEGIN_REPEAT,               1, 0)
BHV_SYMBOL(0, END_REPEAT,                 0)
BHV_SYMBOL(0, END_REPEAT_CONTINUE,        0)
BHV_SYMBOL(0, BEGIN_LOOP,                 0)
BHV_SYMBOL(0, END_LOOP,                   0)
BHV_SYMBOL(0, BREAK,                      0)
BHV_SYMBOL(0, BREAK_UNUSED,               0)
BHV_SYMBOL(1, CALL_NATIVE,                1, PTYPE_FUNC_BHV)
BHV_SYMBOL(0, ADD_FLOAT,                  2, 0, 0)
BHV_SYMBOL(0, SET_FLOAT,                  2, 0, 0)
BHV_SYMBOL(0, ADD_INT,                    2, 0, 0)
BHV_SYMBOL(0, SET_INT,                    2, 0, 0)
BHV_SYMBOL(0, OR_INT,                     2, 0, 0)
BHV_SYMBOL(0, BIT_CLEAR,                  2, 0, 0)
BHV_SYMBOL(0, SET_INT_RAND_RSHIFT,        3, 0, 0, 0)
BHV_SYMBOL(0, SET_RANDOM_FLOAT,           3, 0, 0, 0)
BHV_SYMBOL(0, SET_RANDOM_INT,             3, 0, 0, 0)
BHV_SYMBOL(0, ADD_RANDOM_FLOAT,           3, 0, 0, 0)
BHV_SYMBOL(0, ADD_INT_RAND_RSHIFT,        3, 0, 0, 0)
BHV_SYMBOL(0, CMD_NOP_1,                  1, 0)
BHV_SYMBOL(0, CMD_NOP_2,                  1, 0)
BHV_SYMBOL(0, CMD_NOP_3,                  1, 0)
BHV_SYMBOL(0, SET_MODEL,                  1, 0)
BHV_SYMBOL(1, SPAWN_CHILD,                2, 0, PTYPE_PNTR_BHV)
BHV_SYMBOL(0, DEACTIVATE,                 0)
BHV_SYMBOL(0, DROP_TO_FLOOR,              0)
BHV_SYMBOL(0, SUM_FLOAT,                  3, 0, 0, 0)
BHV_SYMBOL(0, SUM_INT,                    3, 0, 0, 0)
BHV_SYMBOL(0, BILLBOARD,                  0)
BHV_SYMBOL(0, CYLBOARD,                   0)
BHV_SYMBOL(0, HIDE,                       0)
BHV_SYMBOL(0, SET_HITBOX,                 2, 0, 0)
BHV_SYMBOL(0, CMD_NOP_4,                  2, 0, 0)
BHV_SYMBOL(0, DELAY_VAR,                  1, 0)
BHV_SYMBOL(0, BEGIN_REPEAT_UNUSED,        1, 0)
BHV_SYMBOL(1, LOAD_ANIMATIONS,            2, 0, PTYPE_PNTR_ANIM)
BHV_SYMBOL(0, ANIMATE,                    1, 0)
BHV_SYMBOL(1, SPAWN_CHILD_WITH_PARAM,     3, 0, 0, PTYPE_PNTR_BHV)
BHV_SYMBOL(1, LOAD_COLLISION_DATA,        1, PTYPE_PNTR_COL)
BHV_SYMBOL(0, SET_HITBOX_WITH_OFFSET,     3, 0, 0, 0)
BHV_SYMBOL(1, SPAWN_OBJ,                  2, 0, PTYPE_PNTR_BHV)
BHV_SYMBOL(0, SET_HOME,                   0)
BHV_SYMBOL(0, SET_HURTBOX,                2, 0, 0)
BHV_SYMBOL(0, SET_INTERACT_TYPE,          1, 0)
BHV_SYMBOL(0, SET_OBJ_PHYSICS,            8, 0, 0, 0, 0, 0, 0, 0, 0)
BHV_SYMBOL(0, SET_INTERACT_SUBTYPE,       1, 0)
BHV_SYMBOL(0, SCALE,                      2, 0, 0)
BHV_SYMBOL(0, PARENT_BIT_CLEAR,           2, 0, 0)
BHV_SYMBOL(0, ANIMATE_TEXTURE,            2, 0, 0)
BHV_SYMBOL(0, DISABLE_RENDERING,          0)
BHV_SYMBOL(0, SET_INT_UNUSED,             2, 0, 0)
// BHV_SYMBOL(0, SPAWN_WATER_DROPLET,        1, PTYPE_PNTR_???)
BHV_SYMBOL(0, ID,                         1, 0)
BHV_SYMBOL(1, CALL_EXT,                   1, PTYPE_LUAV)
BHV_SYMBOL(1, GOTO_EXT,                   1, PTYPE_LUAV)
BHV_SYMBOL(1, CALL_NATIVE_EXT,            1, PTYPE_LUAV)
BHV_SYMBOL(1, SPAWN_CHILD_EXT,            2, 0, PTYPE_LUAV)
BHV_SYMBOL(1, SPAWN_CHILD_WITH_PARAM_EXT, 3, 0, 0, PTYPE_LUAV)
BHV_SYMBOL(1, SPAWN_OBJ_EXT,              2, 0, PTYPE_LUAV)
BHV_SYMBOL(1, LOAD_ANIMATIONS_EXT,        2, 0, PTYPE_LUAV)
BHV_SYMBOL(1, LOAD_COLLISION_DATA_EXT,    1, PTYPE_LUAV)
